### ISSUE TITLE
Getting null object reference after compile

### ISSUE THREAD

**Issue by lrivera8** [upnext/BeaconControl_Android_SDK#6]
Hi there!
I download the android sdk to change the sdk_config_service_base_url for our server and created a new .aar.

Unfortunately, when I use the library in the project, i get the error while executing the app:

Attempt to read from field 'java.lang.String com.upnext.beaconos.sdk.backend.model.TokenResponse.accessToken' on a null object reference

Here the Android Studio log:

 FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.cirici.androidbase, PID: 7886
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.upnext.beaconos.sdk.backend.model.TokenResponse.accessToken' on a null object reference
            at com.upnext.beaconos.sdk.backend.storage.SdkTokenStorage.storeToken(SdkTokenStorage.java:33)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.storeToken(BeaconControlManagerImpl.java:146)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.storeTokenAndGetTokenResponse(BeaconControlManagerImpl.java:150)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.checkErrorAndGetTokenResponse(BeaconControlManagerImpl.java:156)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.access$300(BeaconControlManagerImpl.java:39)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl$BeaconControlInterceptor.intercept(BeaconControlManagerImpl.java:112)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
            at com.squareup.okhttp.Call.access$100(Call.java:34)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

Thank you in advance!

**Comment by danielnow** [comment]
Hi,

Thanks for reaching out and playing around with our platform.

The error is caused by missing access token. There is performed OAuth 2 authentication to obtain access token.

You may find details at BeconControl page https://beaconcontrol.io/dev/backend-docs in the section 4.1.

Do not hesitate to contact us again if you require any further assistance.

Thanks!

**Comment by lrivera8** [comment]
Hi,
I already changed the client_id and client_secret in the BeaconSDK.getInstance() function for the one in my server application.

Still getting the same error. There is something I should change on the library code to be able to use it with our own server?

Thanks!

**Comment by lrivera8** [comment]
In case it help, just before the error I get this on the logs:

D/BeaconSDK~BeaconService﹕ Start scan.
D/BeaconSDK~BeaconService﹕ Cannot add client, conf is null.
D/ConnectivityManager.CallbackHandler﹕ CM callback handler got msg 524290

**Comment by danielnow** [comment]
Please, use curl to check you will obtain access token:

curl -iX POST 'SERVER_HOST/api/v1/oauth/token' -H "Content-Type: application/json; Accept: application/json" -d '{"client_id":"API_KEY","client_secret":"API_SECRET","os":"android","grant_type":"password","user_id":"USER_ID"}'

Please, fill SERVER_HOST, API_KEY, API_SECRET and USER_ID above. If you obtain access token successfully, then we will know the issue is at the SDK side. Otherwise, user is not known on the server.

**Comment by lrivera8** [comment]
Dear danielnow,
I used the curl and obtained a access token successfully.

Thank you!

**Comment by lrivera8** [comment]
Hi there!
Can I help in anyway with the issue?

**Comment by danielnow** [comment]
Hi,

If you can, please provide us the response you receive from the server.

Thank you.

**Comment by lrivera8** [comment]
Hi,
do you mean the response from the CURL above?

**Comment by danielnow** [comment]
Hi,

I mean response for request to obtain access token. In SDK access token is obtained by sending request to oauth/token endpoint. Response received from the server is mapped to TokenResponse object which may be find in the package com.upnext.beaconos.sdk.backend.model.

To provide response, you may set proxy and see the communication between your mobile phone and server.

If you have any questions, please feel free to write the comments.

Thanks!

**Comment by lrivera8** [comment]
Hi danielnow,
I checked with Charles, and actually, doesn't do the request, I didn't see anything to our server api url.

Kind regards,

**Comment by lrivera8** [comment]
Hi there!
It could be because our server url has the port on it? like "http:url_to_server:5000".

Kind regards,

**Comment by lrivera8** [comment]
Hi there!
I found out I had to add /api/v1 to the config.xml server url.

Anyway, now I am getting another logs:

D/BeaconSDK~BeaconService: Start scan.
 D/BeaconSDK~BeaconService: Cannot add client, conf is null.
 D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
 I/Beacons: {device=android, token=APA91bHmKK75s5NVHmHuySdXLcWoRRHxxd5M7LXs5wbwWrgZNfs39sCzJlfWDX-ylmkt1_edR-Q0acMdd5a7iqpBsQFy_gjvVeQSC6PlvULUoBkkz1tMpESKeE1AsRf8qgRdqoD2Ivjk}
 W/BluetoothCrashResolver: Can't read macs from BluetoothCrashResolverState.txt
 D/BeaconSDK~BeaconService: onBeaconServiceConnect
 D/BeaconSDK~GetConfigurationsResponse: Configurations ranges are invalid.
 D/BeaconSDK~HttpCallMediator: IO_ERROR
 D/BeaconSDK~BeaconServiceHelper: Error in getConfigurations task, IO_ERROR

Any ideas?

**Comment by redoc123** [comment]
Curl will always pass because there is nothing wrong with the server side api response.

I had the same issue today and ended up debugging it.

In my case I am debugging the app on android devise (usb debugging mode). The problem is app is calling refresh token on expired token. I uninstalled the app and re-launched it from android studio. It the worked fine. 

technical explanation: Instead of calling BeaconControlTokenManager.refreshTokenCall() it now calls and BeaconControlTokenManager.getNewTokenCall().

Apparently line 135 in BeaconControlManagerImpl.java: private boolean tokenIsInvalid(TokenResponse token): 

_if (token.createdAt == REFRESH_TOKEN_STRATEGY_NOT_USED || token.expiresIn == REFRESH_TOKEN_STRATEGY_NOT_USED)_ 

does nt make any sense. REFRESH_TOKEN_STRATEGY_NOT_USED whose value is 0 is compared to long values of createdAt and expiresIn.

We should move lines BeaconControlManagerImpl.java 140 & 141 to TokenResponse.java::isValid method.

and BeaconControlManagerImpl::tokenIsInvalid can be avoided (line:113) and directly call TokenResponse.isValid().

Hope this helps.

**Comment by botmonster** [comment]
hi @redoc123 please provide pull request for this fix

**Comment by redoc123** [comment]
@botmonster  here you go: https://github.com/redoc123/BeaconControl_Android_SDK.git

**Comment by junaidyasin** [comment]
@lrivera8 can I please know how did you manage to change the sdk_config_service_base_url?
