### ISSUE TITLE
Getting page not found

### ISSUE THREAD

**Issue by lrivera8** [upnext/BeaconControl_Android_SDK#9]
Hi there!
I changed the server url on the sdk for ours, it detects the beacons, but then in the action webview appears a page not found: http://mobile/coupons/1.

Kind regards,
Laura.

**Comment by jkurdel** [comment]
Hi @lrivera8 

You are getting this error because you didn't set proper coupon_url in your custom backend (unfortunately current default value is misleading):
https://github.com/upnext/BeaconControl/blob/master/config/app_config.rb#L23

Please set this config variable to your backend url - this should fix your problem.

Kind regards,
Jan

**Comment by lrivera8** [comment]
Thank you! It worked!
